apiVersion: apps/v1
kind: Deployment
metadata:
  name: currenttime-flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currenttime-flask-api
  template:
    metadata:
      labels:
        app: currenttime-flask-api
    spec:
      containers:
      - name: currenttime-flask-api
        image: siddiqitaha/currenttime-flask-api:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: currenttime-flask-api-service
spec:
  type: LoadBalancer
  selector:
    app: currenttime-flask-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
